version: 0.2

env:
  variables:
    PYTHONPATH: $CODEBUILD_SRC_DIR
    PYSPARK_PYTHON: python3
    PYSPARK_DRIVER_PYTHON: python3

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - python -m pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Checking versions..."
      - python --version
      - java -version

  build:
    commands:
      - echo "Running unit tests..."
      - pytest -v --disable-warnings --maxfail=1 --junitxml=junit.xml
      - echo "Creating versioned copy for S3..."
      - cp junit.xml junit-$CODEBUILD_BUILD_NUMBER.xml

reports:
  pytest_reports:
    files:
      - junit.xml
    file-format: JUNITXML

artifacts:
  files:
    - junit.xml                # archivo original para CodeBuild UI
    - junit-*.xml              # copia versionada para S3
  discard-paths: yes
  base-directory: .
  s3-prefix: artifacts/        # carpeta en S3 donde se suben los artifacts versionados
